[hebrew]
    welcome_to_the_group = "שלום {} וברוכים הבאים לקבוצה!\nעומדים לרשותך שישים (60) שניות ללחוץ על הכפתור לאשר שאתה לא בוט ;)\nבמידה ולא לחצת, לאחר 60 שניות תיחסם מהקבוצה."
    message_not_for_you = "אני מדמיין או שההודעה הזו לא פונה אליך?🧐"
    welcome = "ברוך הבא!"
    bye = "נחסמת :("
    i_am_a_bot = "אני בוט 🤖"
    i_am_a_human = "אני בן אדם 👨"
    features = ["כפתור 'אני בן אדם' לזיהוי בוטים."]
    bot_was_added = "@jinja היי, אני GroupManagerILBot ואני אעזור לכם בניהול הקבוצה. על מנת להגדיר אותי יש ללחוץ על הכפתור למטה, עד אז אני לא אעבוד. \n\nמה אני מציע ( בנתיים ) :\n{{'►'+this.hebrew.features | join('\n►')}}"
    button_config = "לחץ כאן להגדרה"